@E2EKafka
Feature: Kafka regressions

  @WorkflowKafka
  Scenario Outline: Kafka notification validation - <workflowName> - <testcase>
    Given I have a request for <diagnosticTestTypeHost> service with <requestJSON> on <endPoint>
    Then Verify Post Response <responseCode>
    Then Consume messages from kafka topic for <kafkaResponseTopic> and <expectedNotification>
    Then Validate Kafka messages for response <expectedNotification>

    Examples:
    |testcase                             |workflowName                  |diagnosticTestTypeHost |requestJSON                                              | endPoint                 | responseCode         |expectedNotification |kafkaResponseTopic|
    |Expected outcome code: loopback_completed |loopback completed workflow | devURL|/src/test/resources/testdata/loopback/request/loopback_request.json |v1/loopbackTest |202         |loopback_completed        |notificationInputTopic|
    |Expected outcome code: dpuStatus_completed |dpustatus completed workflow | devURL|/src/test/resources/testdata/dpustatus/request/dpustatus_request.json |v1/dpuStatusTest |202         |dpustatus_completed        |notificationInputTopic|
    |Expected outcome code: dpuportstatus_completed |dpuPortstatus completed workflow | devURL|/src/test/resources/testdata/dpuportstatus/request/dpuportstatus_request.json |v1/dpuPortStatusTest |202         |dpuportstatus_completed        |notificationInputTopic|
    |Expected outcome code: loopback_Failed |loopback completed Failed workflow | devURL|/src/test/resources/testdata/loopback/request/loopback_failed_request.json |v1/loopbackTest |202         |loopback_failed       |notificationInputTopic|
    |Expected outcome code: dpuStatus_Failed |dpustatus completed Failed workflow | devURL|/src/test/resources/testdata/dpustatus/request/dpustatus_failed_request.json |v1/dpuStatusTest |202         |dpustatus_failed        |notificationInputTopic|
    |Expected outcome code: dpuportstatus_Failed |dpuPortstatus completed Failed workflow | devURL|/src/test/resources/testdata/dpuportstatus/request/dpuportstatus_failed_request.json |v1/dpuPortStatusTest |202         |dpuportstatus_failed        |notificationInputTopic|
    |Expected outcome code: loopback_cancelled |loopback cancelled workflow | devURL|/src/test/resources/testdata/loopback/request/loopback_cancelled_request.json |v1/loopbackTest |202         |loopback_cancelled        |notificationInputTopic|
    |Expected outcome code: dpuStatus_cancelled |dpustatus cancelled workflow | devURL|/src/test/resources/testdata/dpustatus/request/dpustatus_cancelled_request.json |v1/dpuStatusTest |202         |dpustatus_cancelled        |notificationInputTopic|
    |Expected outcome code: dpuportstatus_cancelled |dpuPortstatus cancelled workflow | devURL|/src/test/resources/testdata/dpuportstatus/request/dpuportstatus_cancelled_request.json |v1/dpuPortStatusTest |202         |dpuportstatus_cancelled       |notificationInputTopic|
    |Expected outcome code: loopback_rejected|loopback rejected workflow | devURL|/src/test/resources/testdata/loopback/request/loopback_rejected_request.json |v1/loopbackTest |202         |loopback_rejected        |notificationInputTopic|
    |Expected outcome code: dpuStatus_rejected |dpustatus rejected workflow | devURL|/src/test/resources/testdata/dpustatus/request/dpustatus_rejected_request.json |v1/dpuStatusTest |202         |dpustatus_rejected        |notificationInputTopic|
    |Expected outcome code: dpuportstatus_rejected |dpuPortstatus rejected workflow | devURL|/src/test/resources/testdata/dpuportstatus/request/dpuportstatus_rejected_request.json |v1/dpuPortStatusTest |202         |dpuportstatus_rejected        |notificationInputTopic|
    |Expected outcome code: fttcassurancediagnostictest_completed_happy |fttcassurancediagnostictest_completed_happy workflow | devURL|/src/test/resources/testdata/fttcassurancediagnostictest/fttcassurancediagnostictest_post/01_diagnosticRequestMessage.json |v1/sdpFttcAssuranceDiagnosticTest |202         |fttcassurancediagnostictest_completed_happy        |notificationInputTopic|
    |Expected outcome code: fttcassurancediagnostictest_rejected |fttcassurancediagnostictest_rejected workflow | devURL|/src/test/resources/testdata/fttcassurancediagnostictest/fttcassurancediagnostictest_post/02_diagnosticRequestMessage.json |v1/sdpFttcAssuranceDiagnosticTest |202         |fttcassurancediagnostictest_rejected        |notificationInputTopic|
    |Expected outcome code: fttcassurancediagnostictest_dpustatus_failed |fttcassurancediagnostictest_dpustatus_failed workflow | devURL|/src/test/resources/testdata/fttcassurancediagnostictest/fttcassurancediagnostictest_post/03_diagnosticRequestMessage.json |v1/sdpFttcAssuranceDiagnosticTest |202         |fttcassurancediagnostictest_dpustatus_failed        |notificationInputTopic|
    |Expected outcome code: fttcassurancediagnostictest_loopback_failed |fttcassurancediagnostictest_loopback_failed workflow | devURL|/src/test/resources/testdata/fttcassurancediagnostictest/fttcassurancediagnostictest_post/04_diagnosticRequestMessage.json |v1/sdpFttcAssuranceDiagnosticTest |202         |fttcassurancediagnostictest_loopback_failed        |notificationInputTopic|
    |Expected outcome code: fttcassurancediagnostictest_performance_failed |fttcassurancediagnostictest_performance_failed workflow | devURL|/src/test/resources/testdata/fttcassurancediagnostictest/fttcassurancediagnostictest_post/05_diagnosticRequestMessage.json |v1/sdpFttcAssuranceDiagnosticTest |202         |fttcassurancediagnostictest_performance_failed        |notificationInputTopic|
    |Expected outcome code: fttcassurancediagnostictest_dpustatus_cancelled |fttcassurancediagnostictest_dpustatus_cancelled workflow | devURL|/src/test/resources/testdata/fttcassurancediagnostictest/fttcassurancediagnostictest_post/06_diagnosticRequestMessage.json |v1/sdpFttcAssuranceDiagnosticTest |202         |fttcassurancediagnostictest_dpustatus_cancelled        |notificationInputTopic|
    |Expected outcome code: fttcassurancediagnostictest_loopback_cancelled |fttcassurancediagnostictest_loopback_cancelled workflow | devURL|/src/test/resources/testdata/fttcassurancediagnostictest/fttcassurancediagnostictest_post/07_diagnosticRequestMessage.json |v1/sdpFttcAssuranceDiagnosticTest |202         |fttcassurancediagnostictest_loopback_cancelled        |notificationInputTopic|
    |Expected outcome code: fttcassurancediagnostictest_performance_cancelled |fttcassurancediagnostictest_performance_cancelled workflow | devURL|/src/test/resources/testdata/fttcassurancediagnostictest/fttcassurancediagnostictest_post/08_diagnosticRequestMessage.json |v1/sdpFttcAssuranceDiagnosticTest |202         |fttcassurancediagnostictest_performance_cancelled        |notificationInputTopic|
    |Expected outcome code: QS3 |No sync workflow | diagnosticTestRedOpticalHost | \\src\\test\\resources\\testdata\\dignostictest\\oSync\\request\\NoSyncQS3.json | v1/diagnosticTest | 202          | QS3                  |redOpticalKafkaTopic|
    |Expected outcome code: RO2|Red optical workflow | diagnosticTestRedOpticalHost | \\src\\test\\resources\\testdata\\dignostictest\\redoptical\\request\\RedOpticalRO2.json | v1/diagnosticTest | 202          | RO2                  |redOpticalKafkaTopic|
    |Expected outcome:Cancelled|Red optical workflow | diagnosticTestRedOpticalHost | \\src\\test\\resources\\testdata\\dignostictest\\redoptical\\request\\RedOpticalCancelled.json | v1/diagnosticTest | 202          | CANCELLED            |redOpticalKafkaTopic|
    |Expected outcome: Completed Passed|DPU status workflow  | dpuStatusTestHost      | \\src\\test\\resources\\testdata\\dpustatus\\postDpuStatusTest\\00_diagnosticRequest_CompletedPassed.json | v1/dpuStatusTest | 202          | CompletedPassed      |redOpticalKafkaTopic|
    |Expected outcome: Completed Failed|DPU status workflow| dpuStatusTestHost      | \\src\\test\\resources\\testdata\\dpustatus\\postDpuStatusTest\\02_diagnosticRequest_CompletedFailed.json | v1/dpuStatusTest | 202          | CompletedFailed      |redOpticalKafkaTopic|
    |Expected outcome: Rejected|DPU status workflow| dpuStatusTestHost      | \\src\\test\\resources\\testdata\\dpustatus\\postDpuStatusTest\\03_diagnosticRequest_Rejected.json        | v1/dpuStatusTest | 202          | Rejected             |redOpticalKafkaTopic|
    |Expected outcome: Cancelled|DPU status workflow| dpuStatusTestHost      | \\src\\test\\resources\\testdata\\dpustatus\\postDpuStatusTest\\04_diagnosticRequest_Cancelled.json       | v1/dpuStatusTest | 202          | Cancelled            |redOpticalKafkaTopic|
    |Expected outcome code: dpuportreset_completed_happy |dpuportreset_completed_happy workflow | devURL|/src/test/resources/testdata/dpuportreset/dpuportreset_post/00_diagnosticRequest_completed_happy.json |v1/dpuPortReset |202         |dpuportreset_completed_happy        |notificationInputTopic|
    |Expected outcome code: dpuportreset_completed_failed |dpuportreset_completed_failed workflow | devURL|/src/test/resources/testdata/dpuportreset/dpuportreset_post/00_diagnosticRequest_failed.json |v1/dpuPortReset |202         |dpuportreset_completed_failed        |notificationInputTopic|
    |Expected outcome code: dpuportreset_rejected |dpuportreset_rejected workflow | devURL|/src/test/resources/testdata/dpuportreset/dpuportreset_post/00_diagnosticRequest_rejected.json |v1/dpuPortReset |202         |dpuportreset_rejected        |notificationInputTopic|
    |Expected outcome code: fttcactivationsdiagnostictest_completed_happy |fttcactivationsdiagnostictest_completed_happy workflow | devURL|/src/test/resources/testdata/fttcactivationsdiagnostictest/fttcactivationsdiagnostictest_post/01_diagnosticRequestMessage.json |v1/sdpFttcActivationsDiagnosticTest |202         |fttcactivationsdiagnostictest_completed_happy        |notificationInputTopic|
    |Expected outcome code: fttcactivationsdiagnostictest_rejected |fttcactivationsdiagnostictest_rejected workflow | devURL|/src/test/resources/testdata/fttcactivationsdiagnostictest/fttcactivationsdiagnostictest_post/02_diagnosticRequestMessage.json |v1/sdpFttcActivationsDiagnosticTest |202         |fttcactivationsdiagnostictest_rejected        |notificationInputTopic|
    |Expected outcome code: fttcactivationsdiagnostictest_dpustatus_failed |fttcactivationsdiagnostictest_dpustatus_failed workflow | devURL|/src/test/resources/testdata/fttcactivationsdiagnostictest/fttcactivationsdiagnostictest_post/03_diagnosticRequestMessage.json |v1/sdpFttcActivationsDiagnosticTest |202         |fttcactivationsdiagnostictest_dpustatus_failed        |notificationInputTopic|
    |Expected outcome code: fttcactivationsdiagnostictest_dpustatus_cancelled |fttcactivationsdiagnostictest_dpustatus_cancelled workflow | devURL|/src/test/resources/testdata/fttcactivationsdiagnostictest/fttcactivationsdiagnostictest_post/04_diagnosticRequestMessage.json |v1/sdpFttcActivationsDiagnosticTest |202         |fttcactivationsdiagnostictest_dpustatus_cancelled        |notificationInputTopic|
    #Network Performance Test Scenarios
    |Expected outcome code: npt_completed |npt completed workflow        |devURL                 |/src/test/resources/testdata/npt/request/npt_request.json |v1/networkPerformanceTest |202                  |npt_completed         |notificationInputTopic|
    |Expected outcome code: npt_completed |npt completed WO_TC_workflow  |devURL                 |/src/test/resources/testdata/npt/request/npt_request_woTrafficClass.json |v1/networkPerformanceTest |202   |npt_completed         |notificationInputTopic|
    |Expected outcome code: npt_Failed    |npt completed Failed workflow |devURL                 |/src/test/resources/testdata/npt/request/npt_failed_request.json |v1/networkPerformanceTest |202           |npt_failed            |notificationInputTopic|
    |Expected outcome code: npt_cancelled |npt cancelled workflow        |devURL                 |/src/test/resources/testdata/npt/request/npt_cancelled_request.json |v1/networkPerformanceTest |202        |npt_cancelled         |notificationInputTopic|
    |Expected outcome code: npt_rejected  |npt rejected workflow         |devURL                 |/src/test/resources/testdata/npt/request/npt_rejected_request.json |v1/networkPerformanceTest |202         |npt_rejected          |notificationInputTopic|

  Scenario Outline: Jeddis validate response code - <workflowName> - <testcase>
    Given I submit a DiagnosticRequest message via HTTP POST, sending <requestJSON> in the body to <endPoint>
    Then Verify Post Response <responseCode>

    Examples:
      |testcase|workflowName| requestJSON                                                                                          | endPoint         | responseCode |
      |negative HTTP Status codes returned in the response|DPU status workflow| \\src\\test\\resources\\testdata\\dpustatus\\postDpuStatusTest\\04_diagnosticRequest_BadRequest.json | v1/dpuStatusTest | 400          |
